### ISSUE TITLE
"The connection was closed by the client" or "Timeout"

### ISSUE THREAD

**Issue by MaDragon** [ibm-watson-iot/iot-starter-for-android#5]
Hi @robert17 , How can I run the app continuing for one day or one week, to collect the sensor data?

Sometimes the app closed with "The connection was closed by the client" or "Timeout by service" message shown in Bluemix IoT Platform webpage.

I had tried to add a keep alive service to this android app but not working, still have  "The connection was closed by the client" or "Timeout by service" .

Will recreating an Activity do the work? If so, how should I save and restore the Activity State.

Thanks

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
