### ISSUE TITLE
problem getting the location

### ISSUE THREAD

**Issue by IhsenCharfi** [ibm-watson-iot/iot-starter-for-android#7]
I have issues with permission to get location. in utils/locationutils.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
