### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by ahidaka** [ibm-watson-iot/iot-starter-for-android#9]
While I'm using iot-starter_501_v2-1.apk on my android device, Authorization error happens.

Device Side message)
Failed to connect toWatson IoT:
Not authorized to connect (5)

Watson side message)
Closed connection from xxx.xxx.xxx.xxx. The operation is not authorized.

Is there any workaround to avoid this?

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
